version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - "> 5.5.2, < 6"
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - "> 5.5.2, < 6"
  - dependency-name: org.junit.jupiter:junit-jupiter-params
    versions:
    - "> 5.5.2, < 6"
  - dependency-name: net.dv8tion:JDA
    versions:
    - 4.2.0_228
    - 4.2.0_229
